### PR TITLE
Correcting $cancheckin

### PR DESCRIPTION
**Pull request by infograf768**
This lets display the checked_out icon. Needs https://github.com/rdeutz/joomla-cms/pull/9 to be merged first.

### CODE REVIEW

**Comment by infograf768** [comment]
Travis failure does not look related to this patch

**Comment by rdeutz** [comment]
I think we should move this to a helper function instead of having it in the view

**Comment by infograf768** [comment]
Hmm. Eleswhere in Joomla it is in the view. If you have a better solution, let me know

**Comment by rdeutz** [comment]
please check https://github.com/joomla/joomla-cms/pull/13758

**Pull request closed without merging**
